INSERT IGNORE INTO conn_types (identifier, description) VALUES 
	('default','Default settings for missing connection types'),
	('28.8Kbps', 'Old style'),
	('33.6Kbps', 'Old style'),
	('56Kbps', 'Old style'),
	('Modem','Old style'),
	('ISDN','Old style'),
	('Cable', 'Old style'),
	('DSL','Old style'),
	('Satellite','Old style'),
	('Microwave','Old style'),
	('Wireless','Old style'),
	('LAN(T1)','Old style'),
	('LAN(T3)','Old style'),
	('0.005','New style'),
	('0.01','New style'),
	('0.02','New style'),
	('0.05','New style'),
	('0.1','New style'),
	('0.2','New style'),
	('0.5','New style'),
	('1','New style'),
	('2','New style'),
	('5','New style'),
	('10','New style'),
	('20','New style'),
	('50','New style'),
	('100','New style'),
	('1000','New style')
