INSERT IGNORE INTO `client_list` (`name`, `tag_id`, `min_version`, `max_version`, `ban`, `enable`) VALUES
	('DC++', '++', -1, -1, 0, 1),
	('FearDC', 'FearDC', -1, -1, 0, 1),
	('Valknut', 'DCGUI', -1, -1, 0, 1),
	('OperaDC', 'oDC', -1, -1, 0, 1),
	('OperaDC-2', 'o', -1, -1, 0, 1),
	('StrongDC++', 'StrgDC++', -1, -1, 0, 1),
	('ApexDC++', 'ApexDC++', -1, -1, 0, 1),
	('PeerWebDC++', 'PWDC++', -1, -1, 0, 1),
	('FlylinkDC++', 'FlylinkDC++', -1, -1, 0, 1),
	('StrongDC++ SQLite', 'SSQLite++', -1, -1, 0, 1),
	('DC Pro', 'DC:PRO', -1, -1, 0, 1),
	('NMDC', 'DC', -1, -1, 0, 1),
	('iDC++', 'iDC', -1, -1, 0, 1),
	('AirDC++', 'AirDC++', -1, -1, 0, 1),
	('IceDC++', 'IceDC++', -1, -1, 0, 1),
	('DDD++', 'DDD++', -1, -1, 0, 1),
	('EiskaltDC++', 'EiskaltDC++', -1, -1, 0, 1),
	('GreylinkDC++', 'GreylinkDC++', -1, -1, 0, 1),
	('GreylinkDC++ Mod', 'gl++', -1, -1, 0, 1),
	('PeLinkDC++', 'pl++', -1, -1, 0, 1),
	('zDC++', 'zDC++', -1, -1, 0, 1),
	('RSX++', 'RSX++', -1, -1, 0, 1),
	('DiCe++', 'DiCe++', -1, -1, 0, 1),
	('P2P', 'P2P', -1, -1, 0, 1),
	('Peers', 'Peers', -1, -1, 0, 1),
	('Pulse++K', 'Pulse++K', -1, -1, 0, 1),
	('SharaDC', 'SharaDC', -1, -1, 0, 1),
	('Shareaza', 'Shareaza', -1, -1, 0, 1),
	('MLDonkey', 'MLDC', -1, -1, 0, 1),
	('Zion++', 'Z++', -1, -1, 0, 1)
